### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by neo22s** [comment]
@WinterSilence I actually did take a look and left a comment:

image

**Comment by neo22s** [comment]
I see now that the review comment was not "submitted"

**Comment by jstrobel** [comment]
Hmmmm kohana-modules.com doesn't work for me right now :(

**Comment by neo22s** [comment]
It's down :(

**Comment by jstrobel** [comment]
Puh now i get some error page from University of Alberta
> Sorry, the server is having trouble processing the page you requested.
> Some common reasons for this include:
>     The server is misconfigured.
>     The server cannot handle the workload currently placed upon it.

**Comment by toitzi** [comment]
Obsolete with new Website release

**Pull request closed without merging**
